INSERT INTO jobs
(company, title, location, type, description, about_job, responsibilities,
 requirements, skills, applicants, experience, education, salary)
VALUES

    ('TCS','Java Developer','Hyderabad','Full Time',
     'Looking for Java developers with Spring Boot knowledge.',
     'Join enterprise-scale projects and build scalable backend applications.',
     'Develop APIs, Debug code, Participate in code reviews',
     'B.Tech/MCA, Spring Boot, MySQL',
     'Java, Spring Boot, Hibernate, MySQL, Git',
     43,'0-2 Years','B.Tech/MCA','4-8 LPA'),

    ('Infosys','React Developer','Bangalore','Full Time',
     'Frontend developer with React JS experience.',
     'Build responsive user interfaces for enterprise applications.',
     'Create UI components, Consume APIs, Fix bugs',
     'React JS, JavaScript, Responsive Design',
     'React, JavaScript, HTML, CSS, Redux',
     28,'0-2 Years','B.Tech','4-7 LPA'),

    ('Wipro','Backend Developer','Chennai','Full Time',
     'Build and maintain REST APIs using Spring Boot.',
     'Work on backend systems and microservices.',
     'Develop APIs, Database integration, Testing',
     'Java, Spring Boot, SQL',
     'Java, Spring Boot, SQL, Docker',
     35,'1-3 Years','B.Tech/MCA','5-9 LPA'),

    ('Accenture','MERN Stack Developer','Pune','Full Time',
     'Develop scalable web applications using MERN stack.',
     'Work on full-stack projects for global clients.',
     'Frontend development, Backend APIs, Deployment',
     'MongoDB, Express, React, Node',
     'MERN, JavaScript, Git, REST APIs',
     31,'1-3 Years','B.Tech','6-10 LPA'),

    ('Cognizant','Data Analyst','Hyderabad','Full Time',
     'Analyze business data and create reports.',
     'Convert raw data into actionable insights.',
     'Data analysis, Reporting, Dashboard creation',
     'SQL, Statistics, Excel',
     'SQL, Power BI, Excel, Python',
     24,'0-2 Years','B.Tech/BSc','4-8 LPA'),

    ('Capgemini','Cloud Engineer','Mumbai','Full Time',
     'Work on cloud infrastructure and deployments.',
     'Manage cloud environments and CI/CD pipelines.',
     'Deploy applications, Monitor systems, Automation',
     'AWS/Azure, Linux',
     'AWS, Docker, Kubernetes, Linux',
     19,'1-3 Years','B.Tech','6-11 LPA'),

    ('HCL Technologies','Software Engineer','Noida','Full Time',
     'Develop microservices using Java and Spring.',
     'Build enterprise software systems.',
     'Coding, Testing, Documentation',
     'Java, Spring Boot, Microservices',
     'Java, Spring Cloud, MySQL',
     41,'0-2 Years','B.Tech/MCA','5-9 LPA'),

    ('Tech Mahindra','Frontend Engineer','Hyderabad','Full Time',
     'Create responsive UIs using React and Tailwind CSS.',
     'Deliver modern web experiences.',
     'UI Development, Testing, Optimization',
     'React, Tailwind CSS',
     'React, Tailwind, JavaScript',
     26,'0-2 Years','B.Tech','4-8 LPA'),

    ('IBM','Machine Learning Engineer','Bangalore','Full Time',
     'Work with machine learning models and datasets.',
     'Build AI-driven applications.',
     'Model Training, Data Processing, Evaluation',
     'Python, ML, Statistics',
     'Python, TensorFlow, Pandas, NumPy',
     22,'1-3 Years','B.Tech/MTech','8-14 LPA'),

    ('Oracle','Database Administrator','Chennai','Full Time',
     'Manage database systems and optimize queries.',
     'Maintain high-performance database systems.',
     'Backup, Recovery, Query Optimization',
     'Oracle DB, SQL',
     'Oracle, SQL, PL/SQL',
     17,'1-4 Years','B.Tech','6-12 LPA'),

    ('Amazon','SDE I','Hyderabad','Full Time',
     'Build scalable backend services for global applications.',
     'Develop systems used by millions of customers.',
     'Coding, Design, Testing',
     'Data Structures, Algorithms',
     'Java, AWS, Microservices',
     54,'0-2 Years','B.Tech','12-18 LPA'),

    ('Google','Software Developer','Bangalore','Full Time',
     'Design and develop modern web applications.',
     'Create innovative software products.',
     'Development, Testing, Deployment',
     'DSA, Problem Solving',
     'JavaScript, React, Node.js',
     62,'0-2 Years','B.Tech','15-25 LPA'),

    ('Microsoft','Cloud Developer','Hyderabad','Full Time',
     'Develop enterprise-grade cloud solutions.',
     'Build scalable cloud-native applications.',
     'Cloud Development, API Integration',
     'Azure, .NET',
     'Azure, C#, .NET',
     38,'1-3 Years','B.Tech','10-18 LPA'),

    ('Zoho','Full Stack Developer','Chennai','Full Time',
     'Create and maintain full-stack applications.',
     'Develop complete business solutions.',
     'Frontend, Backend, Database Development',
     'JavaScript, SQL',
     'React, Java, MySQL',
     33,'0-2 Years','B.Tech','6-10 LPA'),

    ('Flipkart','Software Engineer','Bangalore','Full Time',
     'Develop e-commerce platform features and services.',
     'Build high-scale online shopping systems.',
     'Coding, Testing, System Design',
     'Java, Databases',
     'Java, Spring Boot, Redis',
     47,'0-2 Years','B.Tech','8-14 LPA');